name: "treebeard"
author: "treebeardtech"
description: "Automatically containerise and run notebooks"
inputs:
  api-key:
    description: "treebeard api key"
    required: false
  notebooks:
    description: "notebooks to run"
    required: false
    default: "**/*ipynb"
  docker-username:
    description: ""
    required: false
  docker-password:
    description: ""
    required: false
  docker-registry:
    description: ""
    required: false
  notebook-env:
    description: "env vars"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
