name: Check Action Dist

on: [push]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test
  blah:
    runs-on: ubuntu-latest
    steps:
      - run: "exit 1"
        id: 'run'
        continue-on-error: true
      - run: '[[ ${{ steps.run.outcome }} == "failure" &&  ${{ steps.run.conclusion }} == "success" ]]'

  blahs:
    runs-on: ubuntu-latest
    steps:
      - run: "exit 0"
        id: 'run'
        continue-on-error: true
      - run: '[[ ${{ steps.run.outcome }} == "failure" &&  ${{ steps.run.conclusion }} == "success" ]]'
