name: E2E Test

on: [push]

jobs:
  hello_treebeard:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: './'
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './examples/hello_treebeard'
          debug: 'true'

  google_cloud_storage:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: './'
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './examples/google_cloud_storage'
          notebook-env: |
            GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
          debug: 'true'


