name: E2E Test

on: [push]

jobs:
  hello_treebeard:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: './'
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-registry: gcr.io/treebeard-259315/tests
          path: './examples/hello_treebeard'
          debug: 'true'

  google_cloud_storage:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: './'
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-registry: gcr.io/treebeard-259315/tests
          path: './examples/google_cloud_storage'
          debug: 'true'
        env:
          TB_GCP_SERVICE_ACCOUNT_KEY: "${{ secrets.GCP_SA_KEY }}" # TB_ prefix directs treebeard to forward env to container



  virtualenv:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: "./"
        with:
          api-key: ${{ secrets.TREEBEARD_API_KEY }}
          docker-registry: gcr.io/treebeard-259315/tests
          debug: "true"
          path: './integration-test/virtualenv'
        env:
          TREEBEARD_USER_NAME: 'd8a0c5b6c9'
      - name: Check uploads
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/main.ipynb"
          wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/another.ipynb"
          wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/subdir/another.ipynb"
