name: Install test

on: [push]

jobs:
  multi_os_install:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install treebeard
        run: |
          pip install -e ./treebeard-lib