name: Integration Test

on: [push]

jobs:
  conda:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: "./"
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './integration-test/conda'

  virtualenv:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: "./"
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './integration-test/virtualenv'
      - name: Check uploads
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/main.ipynb"
          wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/another.ipynb"
          wget "https://api.treebeard.io/d8a0c5b6c9/virtualenv/$branch/subdir/another.ipynb"

  dagster:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: "./"
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './integration-test/dagster'
  failing_build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: "./"
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './integration-test/failing_build'
        continue-on-error: true
      - run: "false"
  failing_notebook:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - uses: "./"
        with:
          docker-registry: gcr.io/treebeard-259315/tests
          path: './integration-test/failing_notebook'
        continue-on-error: true
      - run: "false"